#!/bin/bash -eu

die() { echo $* >&2; exit -1; }

exec > /dev/null

usage="usage: $0 <somerepo>.git [commits]"
[ $# -lt 2 ] && die $usage

repo=${1:?$usage}
[ "${repo%.git}" = "$repo" ] && die $usage   # reponame must end in '.git'
repo=${repo#file://} # trim off "file://" if it's there

clone=$(basename ${repo/.git/}) # local copy

readme=README.$clone
shift

initialize_blank_repo=""
if [ "$1" = "init" ]; then
  initialize_blank_repo=1
  shift
fi

export commits=${*:-}

create-repo-from() {
  local clone=$1
  mkdir -p $clone
  pushd $clone
  touch $readme
  git init
  git add .
  git commit -m"initial"
  popd
  git clone --bare $clone $repo
  rm -rf $clone
  git clone file://$( readlink -f $repo )
}

if [ "$initialize_blank_repo" ]; then
  rm -rf $repo $clone
fi

if ! [ -d $repo ]; then
  create-repo-from $clone
fi

pushd $clone
[ -d .git ] && git pull # grab any updates

for i in $commits; do
  echo commit $i >> $readme
  git add .
  git commit -m"Commit $i"
done

git push
