#!/bin/bash -eu

# utility routine
die() { echo $* >&2; exit -1; }

# error messages only
exec > /dev/null

# parse args
usage="usage: $0 <somerepo>.git [commits]"
[ $# -lt 2 ] && die $usage

repo=${1:?$usage}
[ "${repo%.git}" = "$repo" ] && die $usage   # reponame must end in '.git'
repo=${repo#file://} # trim off "file://" if it's there

clone=$(basename ${repo/.git/}) # local copy

readme=README.$clone
shift

initialize_blank_repo=""
if [ "$1" = "init" ]; then
  initialize_blank_repo=1
  shift
fi

export commits=${*:-}

# create a bare repo from an existing working copy
create-repo-from() {
  local clone=$1
  mkdir -p $clone
  cd $clone
  touch $readme
  git init -q
  git add .
  git commit -q -m"initial"
  cd ~-
  git clone -q --bare $clone $repo
  rm -rf $clone
  git clone -q file://$( readlink -f $repo )
}

# "init" arg says "wipe out old stuff, start from scratch"
if [ "$initialize_blank_repo" ]; then
  rm -rf $repo $clone
fi

if ! [ -d $repo ]; then
  create-repo-from $clone
fi

# bring the clone up-to-date, then add new commits and push
cd $clone
[ -d .git ] && git pull -q # grab any updates

for i in $commits; do
  echo commit $i >> $readme
  git add .
  git commit -q -m"Commit $i"
done

git push -q
